# Versi development dengan hot reload
FROM golang:1.25-alpine AS dev

WORKDIR /app

# Install air untuk hot reload
RUN go install github.com/cosmtrek/air@v1.51.0

# Install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Expose port
EXPOSE 8871

# Run air untuk hot reload
CMD ["air", "-c", ".air.toml"]